server:
  port: ${GATEWAY_PORT:8080}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: review
          uri: http://localhost:8082
          predicates:
            - Path=/products/{id}/reviews/**
        - id: product
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
management:
  endpoints:
    web:
      exposure:
        include: gateway
